WMC\Symfony\AclBundle\Provider\Doctrine\ClassFieldTargetIdentity:
    type: entity
    manyToOne:
      class:
         column: class_identity
         targetEntity: ClassTargetIdentity
         cascade: [ persist, merge ]      
