WMC\Symfony\AclBundle\Provider\Doctrine\ClassFieldTargetIdentity:
    type: entity
    manyToOne:
      class:
         joinColumn: { name: class_identity_id }
         targetEntity: ClassTargetIdentity
         cascade: [ persist, merge ]      
