WMC\Symfony\AclBundle\Provider\Doctrine\Entry:
    type: entity
    table: acl_entries
    id:
      id:
         type: integer
         generator: { strategy: AUTO }
    fields:
      permission:
         type: string
         length: 32
    manyToOne:
      targetIdentity:
         joinColumn: { name: target_identity_id }
         targetEntity: AbstractTargetIdentity
         cascade: [ persist, merge ]
      securityIdentity:
         joinColumn: { name: security_identity_id }
         targetEntity: AbstractSecurityIdentity
         cascade: [ persist, merge ]
