WMC\Symfony\AclBundle\Provider\Doctrine\ObjectFieldTargetIdentity:
    type: entity
    manyToOne:
      object:
         joinColumn: { name: object_identity_id }
         targetEntity: ObjectTargetIdentity
         cascade: [ persist, merge ]      
      classField:
         joinColumn: { name: class_field_identity_id }
         targetEntity: ClassFieldTargetIdentity
         cascade: [ persist, merge ]      
