parameters:
    wmc.acl.entity_manager.name: default
    # wmc.acl.provider.class: WMC\Symfony\AclBundle\
    wmc.acl.voter.class: WMC\Symfony\AclBundle\Voter\AclVoter
    wmc.acl.permission.map.class: WMC\Symfony\AclBundle\Permission\BasicPermissionMap

services:
    # wmc.acl.provider:
    #     class: %wmc.acl.provider.class%
    #     arguments:
    #         -
    #     public: false

    wmc.acl.permission.map:
        class: %wmc.acl.permission.map.class%
        public: false

    # wmc.acl.voter.class:
    #     class: %wmc.acl.voter.basic_permissions%
    #     arguments:
    #         - @wmc.acl.provider
    #         - @wmc.acl.permission.map
    #         - @?logger
    #     tags:
    #         - { name: monolog.logger, channel: security }
    #         - { name: security.voter, priority: 255 }
    #     public: false
