imports:
    - { resource: access_granting_strategies.yml }

parameters:
    wmc.acl.provider.def.class: WMC\Symfony\AclBundle\Provider\AbstractAclProvider
    wmc.acl.provider.security_factory.class: WMC\Symfony\AclBundle\Domain\AclSecurityIdentityFactory
    wmc.acl.provider.target_factory.class: WMC\Symfony\AclBundle\Domain\AclTargetIdentityFactory

    wmc.acl.permission_map.class: WMC\Symfony\AclBundle\Permission\BasicPermissionMap

    wmc.acl.voter.class: WMC\Symfony\AclBundle\Voter\AclVoter

services:
    wmc.acl.provider.def:
        class: %wmc.acl.provider.def.class%
        abstract: true
        arguments:
            - @wmc.acl.provider.security_factory
            - @wmc.acl.provider.target_factory

    wmc.acl.provider.security_factory:
        class: %wmc.acl.provider.security_factory.class%

    wmc.acl.provider.target_factory:
        class: %wmc.acl.provider.target_factory.class%

    wmc.acl.permission_map:
        class: %wmc.acl.permission_map.class%

    wmc.acl.voter:
        class: %wmc.acl.voter%
        arguments:
            - @wmc.acl.provider
            - @wmc.acl.permission_map
            - @wmc.acl.voter.strategy
            - @?logger
        tags:
            - { name: monolog.logger, channel: security }
            - { name: security.voter, priority: 255 }
